### PR TITLE
Get ip from config as port

### PR DESCRIPTION
**Pull request by Sephiroth-Lin**
Get ip from config is more reasonable then set 0.0.0.0 in the code directly.
Now user can set ip in application.conf like below:

appConf{
	# this ip on which to deploy the apis
	web.services.ip=9.91.12.117
	# the port on which to deploy the apis
	web.services.port=8097
        ...
}

### CODE REVIEW

**Comment by raduchilom** [comment]
@Sephiroth-Lin , can you add the web.services.ip property in the application.properties file, just like you did in the comment above(with the default ip 0.0.0.0) ?

**Comment by Sephiroth-Lin** [comment]
@raduchilom, I have add the web.services.ip property in the application.conf file, thank you!

**Comment by raduchilom** [comment]
@Sephiroth-Lin , please set the ip to 0.0.0.0 instead of 9.91.12.117, as it should be default. Then I will merge the request. Thank you.

**Comment by Sephiroth-Lin** [comment]
@raduchilom, please merge the request. Thank you.

**Comment by raduchilom** [comment]
Done. Thank you.

**Pull request merged**
